/**
 * DaDaPush Public API
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Action from './Action';

/**
 * The MessagePushRequest model module.
 * @module model/MessagePushRequest
 * @version 1.0.0
 */
class MessagePushRequest {
    /**
     * Constructs a new <code>MessagePushRequest</code>.
     * @alias module:model/MessagePushRequest
     * @param content {String} message content
     * @param needPush {Boolean} when value is false, will not send client push
     * @param title {String} message title
     */
    constructor(content, needPush, title) { 
        
        MessagePushRequest.initialize(this, content, needPush, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content, needPush, title) { 
        obj['content'] = content;
        obj['needPush'] = needPush;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>MessagePushRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagePushRequest} obj Optional instance to populate.
     * @return {module:model/MessagePushRequest} The populated <code>MessagePushRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagePushRequest();

            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ApiClient.convertToType(data['actions'], [Action]);
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('needPush')) {
                obj['needPush'] = ApiClient.convertToType(data['needPush'], 'Boolean');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * action size range is 0,3
 * @member {Array.<module:model/Action>} actions
 */
MessagePushRequest.prototype['actions'] = undefined;

/**
 * message content
 * @member {String} content
 */
MessagePushRequest.prototype['content'] = undefined;

/**
 * when value is false, will not send client push
 * @member {Boolean} needPush
 */
MessagePushRequest.prototype['needPush'] = undefined;

/**
 * message title
 * @member {String} title
 */
MessagePushRequest.prototype['title'] = undefined;






export default MessagePushRequest;

