/**
 * DaDaPush Public API
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Action from './Action';

/**
 * The MessageObject model module.
 * @module model/MessageObject
 * @version 1.0.0
 */
class MessageObject {
    /**
     * Constructs a new <code>MessageObject</code>.
     * @alias module:model/MessageObject
     * @param channelName {String} 
     * @param content {String} 
     * @param createdAt {String} 
     * @param id {Number} 
     * @param title {String} 
     */
    constructor(channelName, content, createdAt, id, title) { 
        
        MessageObject.initialize(this, channelName, content, createdAt, id, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, channelName, content, createdAt, id, title) { 
        obj['channelName'] = channelName;
        obj['content'] = content;
        obj['createdAt'] = createdAt;
        obj['id'] = id;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>MessageObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageObject} obj Optional instance to populate.
     * @return {module:model/MessageObject} The populated <code>MessageObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageObject();

            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ApiClient.convertToType(data['actions'], [Action]);
            }
            if (data.hasOwnProperty('channelName')) {
                obj['channelName'] = ApiClient.convertToType(data['channelName'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * action size range is 0,3
 * @member {Array.<module:model/Action>} actions
 */
MessageObject.prototype['actions'] = undefined;

/**
 * @member {String} channelName
 */
MessageObject.prototype['channelName'] = undefined;

/**
 * @member {String} content
 */
MessageObject.prototype['content'] = undefined;

/**
 * @member {String} createdAt
 */
MessageObject.prototype['createdAt'] = undefined;

/**
 * @member {Number} id
 */
MessageObject.prototype['id'] = undefined;

/**
 * @member {String} title
 */
MessageObject.prototype['title'] = undefined;






export default MessageObject;

