/**
 * DaDaPush Public API
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessagePushResponse model module.
 * @module model/MessagePushResponse
 * @version 1.0.0
 */
class MessagePushResponse {
    /**
     * Constructs a new <code>MessagePushResponse</code>.
     * @alias module:model/MessagePushResponse
     * @param messageId {Number} 
     */
    constructor(messageId) { 
        
        MessagePushResponse.initialize(this, messageId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, messageId) { 
        obj['messageId'] = messageId;
    }

    /**
     * Constructs a <code>MessagePushResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagePushResponse} obj Optional instance to populate.
     * @return {module:model/MessagePushResponse} The populated <code>MessagePushResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagePushResponse();

            if (data.hasOwnProperty('messageId')) {
                obj['messageId'] = ApiClient.convertToType(data['messageId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} messageId
 */
MessagePushResponse.prototype['messageId'] = undefined;






export default MessagePushResponse;

