/**
 * DaDaPush Public API
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageObject from './MessageObject';

/**
 * The PageResponseOfMessageObject model module.
 * @module model/PageResponseOfMessageObject
 * @version 1.0.0
 */
class PageResponseOfMessageObject {
    /**
     * Constructs a new <code>PageResponseOfMessageObject</code>.
     * @alias module:model/PageResponseOfMessageObject
     */
    constructor() { 
        
        PageResponseOfMessageObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageResponseOfMessageObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageResponseOfMessageObject} obj Optional instance to populate.
     * @return {module:model/PageResponseOfMessageObject} The populated <code>PageResponseOfMessageObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageResponseOfMessageObject();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [MessageObject]);
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/MessageObject>} content
 */
PageResponseOfMessageObject.prototype['content'] = undefined;

/**
 * @member {Number} totalElements
 */
PageResponseOfMessageObject.prototype['totalElements'] = undefined;

/**
 * @member {Number} totalPages
 */
PageResponseOfMessageObject.prototype['totalPages'] = undefined;






export default PageResponseOfMessageObject;

