/**
 * DaDaPush Public API
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessagePushResponse from './MessagePushResponse';

/**
 * The ResultOfMessagePushResponse model module.
 * @module model/ResultOfMessagePushResponse
 * @version 1.0.0
 */
class ResultOfMessagePushResponse {
    /**
     * Constructs a new <code>ResultOfMessagePushResponse</code>.
     * @alias module:model/ResultOfMessagePushResponse
     * @param code {Number} 
     * @param errmsg {String} 
     */
    constructor(code, errmsg) { 
        
        ResultOfMessagePushResponse.initialize(this, code, errmsg);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, errmsg) { 
        obj['code'] = code;
        obj['errmsg'] = errmsg;
    }

    /**
     * Constructs a <code>ResultOfMessagePushResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResultOfMessagePushResponse} obj Optional instance to populate.
     * @return {module:model/ResultOfMessagePushResponse} The populated <code>ResultOfMessagePushResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResultOfMessagePushResponse();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = MessagePushResponse.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('errmsg')) {
                obj['errmsg'] = ApiClient.convertToType(data['errmsg'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} code
 */
ResultOfMessagePushResponse.prototype['code'] = undefined;

/**
 * @member {module:model/MessagePushResponse} data
 */
ResultOfMessagePushResponse.prototype['data'] = undefined;

/**
 * @member {String} errmsg
 */
ResultOfMessagePushResponse.prototype['errmsg'] = undefined;






export default ResultOfMessagePushResponse;

